before_commands:
    - "composer install --prefer-dist"

tools:
    external_code_coverage: false
    php_mess_detector: true
    php_code_sniffer: true
    php_analyzer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_sim: false
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor/*, doc/*]
filter:
    excluded_paths: [vendor/*, doc/*]
